raylib-cs/raylib-cs

Bindings/Extensions.cs
v2.w > v2.w would  always be false.
=> Pretty sure this is a typo.

Raylib-cs.sln, Raylib-cs/Platform.cs, Raylib-cs/Raylib-cs.csproj, Raylib-cs/Raylib-cs.targets
Added Platform.cs - to copy (correct) native library at runtime (for netfx)
`.targets` file now copies `runtimes/` folder to output directory
minor bug fix in sln file.
Fixes #43
=> Runtime handling of native libraries

Raylib-cs/Rlgl.cs
The capital `B` in the `Framebuffer` externs prevented calling the right Raylib function
=> Fixed capitalisation on Framebuffer externs

Raylib-cs/Raylib.cs
I stumbled upon this while trying to unbind the default escape key to prevent accidental closing of the window.
Right now I'm doing it like this
```c#
Raylib.SetExitKey(0);
```
but I think it'd be more readable if we had something like this.
```c#
Raylib.SetExitKey(KeyboardKey.KEY_NULL);
```
[`KEY_NULL` is also part of raylib.h](https://github.com/raysan5/raylib/blob/f9bab14fdb61ec7b6d407a4d3f742414c2842d50/src/raylib.h#L513)
=> Added missing KEY_NULL to KeyboardKey enum

Raylib-cs/types/Raylib.Utils.cs
Changed the frames argument in LoadImageAnim to be a out parameter.
According to Ray, frames should have the number of frames in the animation and using a out parameter seems to be correct way in C#.
I also implemented the example textures_gif_player to test it. I will do a PR when the examples get updated with the new package.
=> Fixed LoadImageAnim frames argument.

.github/workflows/build.yml
libraylib.dylib contains native code for both x86 & arm64 
Fixes #137
=> Copy MacOS native lib to arm64 native folder

Raylib-cs/types/native/CBool.cs
I realized not everyone is familiar with the usage of object initializers - especially new users to the language and beginner gamedevs - so I decided to add some constructors and fix an issue created due to a bad cast (the boolean value would come up as false if assigned any multiple of 256).
=> Created CBool's ctors, fixed casting issue

Raylib-cs/interop/Raymath.cs
Both functions were incorrect. Vector2Clamp was missing arguments and MatrixNormalize was removed from raylib.
=> Fix Vector2Clamp and remove MatrixNormalize

README.md
I accidentally made the mistake of trying to use NuGet in the solution folder and it took a few minutes to figure out what I was doing wrong.
So, I added this sentence here to help clarify what to do for this (probably common) problem since Visual Studio is fairly likely to start the working directory for the command prompt in the solution directory, which may not be the same as the project directory. 
I think since raylib attracts many new users it is best to make the install info as easy as possible, thus my justification for adding this here. 
Installs should be as frictionless as possible. I hope you'll consider adding my suggestion here. 🙂
=> Added some help info for NuGet use.

Raylib-cs/types/Transform.cs
I fixed this bug: https://github.com/ChrisDill/Raylib-cs/issues/157
=> Fix `Transform.rotation` use `Vector4` instead of `Quaternion`

Raylib-cs.sln, Raylib-cs/types/Raylib.Utils.cs
Adding the four following method overloads will make unsafe code blocks unnecessary for fast texture updates.
=> Add managed methods for updating textures

.github/workflows/build.yml
based on https://docs.github.com/en/actions/using-github-hosted-runners/customizing-github-hosted-runners
> **Note:** Always run `sudo apt-get update` before installing a package. In case the `apt` index is stale, this command fetches and re-indexes any available packages, which helps prevent package installation failures.
this should fix ci failing when building linux on #181 and #171
=> Fix linux build

Raylib-cs.sln, Raylib-cs/Raylib-cs.csproj, Raylib-cs/types/Raylib.Utils.cs, Raylib-cs/types/native/AnsiBuffer.cs, Raylib-cs/types/native/UTF8Buffer.cs
Fix for #184. The issue was that raylib text drawing functions do not use ansi - rather UTF8.
These changes should fix the issue by converting to the correct format depending on what each util method needs.
=> [Fix #184] Seperate UTF8 from Ansi

.github/workflows/build.yml, Examples/Textures/ImageGeneration.cs, README.md, Raylib-cs.Tests/RaylibTests.cs, Raylib-cs/Build.props, Raylib-cs/interop/Raylib.cs, Raylib-cs/interop/Raymath.cs, Raylib-cs/interop/Rlgl.cs, Raylib-cs/types/Core.cs, Raylib-cs/types/Model.cs, Raylib-cs/types/Music.cs, Raylib-cs/types/Raylib.Utils.cs, Raylib-cs/types/Sound.cs, Raylib-cs/types/Wave.cs
This pull request is a work in progress (WIP).
I have initiated the process by beginning the port to `Raylib-5.0.0`.
Issue: https://github.com/ChrisDill/Raylib-cs/issues/209
=> Port to Raylib-5.0.0

.github/workflows/build.yml
This PR enables the Desktop platform to operate seamlessly with `OpenGL-4.3`.
Info:
Windows: `OpenGL-4.3`
Linux: `OpenGL-4.3`
Osx: `OpenGL-3.3`
Android: `OpenGL-ES 2.0`
=> Update Desktop to OpenGL 4.3

.github/workflows/build.yml, Raylib-cs.Native/Raylib-cs.Native.csproj
Looking more into it, the default version change would cause issues with older GPUs. Decided instead to remove for now and leave a flag for it that can be commented out in the native project for further testing.
=> Revert default graphics version change

.github/workflows/build.yml
Moves the GitHub Action to the latest Ubuntu LTS (`20.04`) to give wider compatibility.
Closes https://github.com/ChrisDill/Raylib-cs/issues/222
=> Pin to Ubuntu 20.04

Raylib-cs/types/AudioCallback.cs, Raylib-cs/types/AudioMixed.cs, Raylib-cs/types/Raylib.Utils.cs
Utilizing delegates. Attaching a callback to the audio is made much more simple.
```c#
using Raylib_cs;
using System;
using System.Numerics;
static class Synthesizer
{
const int width = 1280;
const int height = 960;
static int shape = 0;       // The shape of the wave
static float position = 0f; // The sin wave position
static float volume = .5f;  // The sin wave amplitude
static float pitch = .5f;   // The sin wave frequency
static void Synth(Span<float> buffer)
{
for (int i = 0; i < buffer.Length; i += 2)
{
position += pitch / 10f;                   // Move the wave position
position = Raymath.Wrap(position, 0f, 2f); // Wrap around
float wave = float.SinPi(position);        // The sin wave
if (shape == 1)
{
wave = float.AsinPi(wave) * 2f;        // Triangle wave
}
else if (shape == 2)
{ …
```
=> AttachAudioMixedProcessor Utils for easy callback

Raylib-cs/interop/Raylib.cs, Raylib-cs/types/Rectangle.cs
* Fixes issue with ExportImageToMemory in #244
* Fixes formatting for consistency
=> Fix ExportImageToMemory return type and update formatting

Examples/Models/DynamicMesh.cs, Raylib-cs/types/Mesh.cs, Raylib-cs/types/Raylib.Utils.cs
The UpdateMeshBuffer Method is important for updating GPU mesh data repeatedly in a performant manner.
This pull request intends to add a safe utility version of this method by accepting a span wrapper of the data rather than a pointer.
This method (including the interop version) requires an index to whichever buffer the user wishes to update—for example vertices, texture coordinates, colors etcetera. This is why I added VboIdIndex<Type> constants to the mesh class to help users access the right vertex buffer object (VBO) ID for the UpdateMeshBuffer Method.
For whatever reason raysan5/raylib does not include an enum or definitions for these VBO indexes. The closest thing I could find to these indexes being defined anywhere was in the raylib source code in …
=> Safe UpdateMeshBuffer Util Method

Raylib-cs/Raylib-cs.csproj
This package is no longer required, because it's part of the standard library now.
=> Remove package System.Numerics.Vectors

Raylib-cs/types/Transform.cs
Hi!
I don't wanna be the guy that only fixes typos, but I noticed this while working on my game and I thought it was better to fix it rather than leaving it.
I made this match the [Raylib source comment](https://github.com/raysan5/raylib/blob/master/src/raylib.h#L391).
Love this project - thank you!
=> Fix typo in Transform struct summary

Raylib-cs/types/Image.cs
Fix incorrect mapping between raylib-cs and raylib for PixelFormat elements that appear after UncompressedR32G32B32A32.
=> Add missing PixelFormat elements

.github/workflows/build.yml, Examples/Examples.csproj, Raylib-cs.Native/Native.cs, Raylib-cs.Native/Raylib-cs.Native.csproj, Raylib-cs.Tests/Raylib-cs.Tests.csproj, Raylib-cs/Raylib-cs.csproj
We don't want to remove old runtimes unless there is a need to do so. This way, we can continue to support projects that don't wish to update their runtime but still enable users that do update their runtime to benefit.
Fixes #295
=> Enable Targeting .Net 8 

README.md
Added notice about deploying for Windows via NativeAOT and the requirement for `STAThread` to the main function to prevent crashes.
See https://github.com/raylib-cs/raylib-cs/issues/301
=> Add STAThread notice to README
