raylib-cs/raylib-cs

Bindings/Easings.cs, Bindings/Physac.cs, Bindings/Raygui.cs, Bindings/Raylib.cs, Bindings/Raymath.cs
=> Changing Dllimport calling conventions to Cdecl

Bindings/Raylib.cs, Examples/core/core_drop_files.cs, Examples/models/models_material_pbr.cs, Examples/models/models_mesh_picking.cs, Examples/text/text_ttf_loading.cs
You may want to inspect the function before merge.
=> Dropfiles fix

Raylib-cs/Easings.cs, Raylib-cs/Raylib.cs
As per quick discussion on Discord, I've checked the necessary and updated as a PR
=> Convert all Math calls to MathF to avoid conversions

README.md
Clarified Physac & Raygui support
=> Clarify Physac & Raygui Support

.github/workflows/build.yml, Raylib-cs/Raylib-cs.csproj, app.config
=> Github Actions for Nuget Releases

Raylib-cs/Raylib-cs.csproj, Raylib-cs/types/Color.cs
[https://docs.microsoft.com/en-us/lifecycle/products/microsoft-net-and-net-core](https://docs.microsoft.com/en-us/lifecycle/products/microsoft-net-and-net-core)
=> Make the color palette readonly fields

Raylib-cs/types/native/CBool.cs
I tried to explain every design choice I made inside the CBool.cs file via comments. They can be left as information for the users if converted in summary blocks, but they're mostly descriptive, so they can also be removed without any side-effects on the understanding of the code! :D
=> Updated CBool to have a greater utility, closer to how C++'s booleans operate

.github/workflows/build.yml, README.md, Raylib-cs/Raylib-cs.csproj, Raylib-cs/interop/Raylib.cs, Raylib-cs/interop/Raymath.cs, Raylib-cs/interop/Rlgl.cs, Raylib-cs/types/Raylib.Utils.cs
Small release with some bug fixes and comment changes.
=> Point release 4.0.0.2

README.md, Raylib-cs/Raylib-cs.csproj, Raylib-cs/interop/Raylib.cs, Raylib-cs/interop/Raymath.cs, Raylib-cs/interop/Rlgl.cs, Raylib-cs/types/Core.cs, Raylib-cs/types/Input.cs, Raylib-cs/types/Raylib.Utils.cs, Raylib-cs/types/native/CBool.cs, Raylib-cs/types/native/FilePathList.cs
- Update bindings to use raylib 4.2.0.
- Review comments and utils.
=> Update to raylib 4.2

Raylib-cs/interop/Raylib.cs
=> Comment of "IsCursorOnScreen" fixed

Raylib-cs/interop/Raylib.cs, Raylib-cs/interop/Raymath.cs, Raylib-cs/interop/Rlgl.cs, Raylib-cs/types/Audio.cs, Raylib-cs/types/BoundingBox.cs, Raylib-cs/types/Camera2D.cs, Raylib-cs/types/Camera3D.cs, Raylib-cs/types/Color.cs, Raylib-cs/types/Font.cs, Raylib-cs/types/Image.cs, Raylib-cs/types/Input.cs, Raylib-cs/types/Logging.cs, Raylib-cs/types/Material.cs, Raylib-cs/types/Mesh.cs, Raylib-cs/types/Model.cs, Raylib-cs/types/NPatchInfo.cs, Raylib-cs/types/Ray.cs, Raylib-cs/types/Raylib.Utils.cs, Raylib-cs/types/Rectangle.cs, Raylib-cs/types/RenderBatch.cs, Raylib-cs/types/RenderTexture2D.cs, Raylib-cs/types/Shader.cs, Raylib-cs/types/Texture2D.cs, Raylib-cs/types/Transform.cs, Raylib-cs/types/native/CBool.cs, Raylib-cs/types/native/FilePathList.cs, Raylib-cs/types/native/UTF8Buffer.cs
Description
====
This Pull Request ensures that all variables and methods are named correctly, adhering to the naming conventions outlined by the C# rules.
https://github.com/ChrisDill/Raylib-cs/issues/163
=> [Fix] Corrected the names of methods, variables, and other elements.

.github/workflows/build.yml
this will solve #118 it also has android build still work in progress https://github.com/anggape/Raylib-cs/tree/android, currently i only tested on windows-x64 and linux-x64, i dont have any macos laying around
=> build raylib from sources

.github/workflows/build.yml, Raylib-cs/Raylib-cs.csproj
=> Include snupkg in release & Enable SourceLink

Raylib-cs/types/Raylib.Utils.cs
Issue: https://github.com/ChrisDill/Raylib-cs/issues/178
=> Adding a string method for `OpenURL` and `SetGamepadMappings`

Raylib-cs.Tests/BlittableHelper.cs, Raylib-cs/interop/Rlgl.cs
Fixed names in Rlgl.
Issue: https://github.com/ChrisDill/Raylib-cs/issues/163
=> Fixed names in Rlgl

.github/workflows/build.yml, Directory.Build.props, Raylib-cs.Android/Raylib-cs.Android.csproj, Raylib-cs.Android/RaylibActivity.cs, Raylib-cs.Android/android.patch, Raylib-cs.sln, Raylib-cs/Raylib-cs.csproj
this is simplified version of #171 
i already use this build on private project, and confirm it was working, but if someone want to test i show the examples here https://github.com/anggape/raylib-cs-samples or download the apk here https://github.com/anggape/raylib-cs-samples/actions/runs/5948975517
the problem i found is that you cant run on debug build but works fine on release build, i will investigate this in the future,
the other problem is when you initialize window you should set width and height to 0 for example
```cs
Raylib.InitWindow(0, 0, "");
```
otherwise touch position has some offset
=> Android rewrite

Examples/Core/InputGamepad.cs
I've fixed the problems associated with this file which I detailed in my issue report [here](https://github.com/ChrisDill/Raylib-cs/issues/195) (issue #195).
My version of Raylib-cs is slightly different from the bleeding edge master branch but still recent, and my project setup is slightly different too, but I think this change should still work. You should test it to check though.
I didn't use the manual method for setting up Raylib-cs. I used the automatic one using the package management system (simple command line install).
The current master branch for Raylib-cs says it has a broken build, whereas the version I'm using doesn't have that. So, this code change was tested on my version because I don't know whether I'd be able to get the currently broken (but most recent) master branch …
=> Fixed problem where Xbox controller wouldn't appear for `InputGamepad`.

Raylib-cs/types/Raylib.Utils.cs
Added camera methods without pointers.
=> [Bug] Added camera methods without pointers.

Raylib-cs/interop/Raylib.cs, Raylib-cs/types/Raylib.Utils.cs
=> Fix GenImageText bug/add utility method

Raylib-cs/types/Rectangle.cs
Adds constructors and the Position and Size properties to facilitate the creation and modification of Rectangle fields.
=> Rectangle constructors and properties using Vector2

Examples/Examples.csproj, Raylib-cs.Tests/Raylib-cs.Tests.csproj, Raylib-cs/Raylib-cs.csproj
=> Update LangVersion to 12

Raylib-cs/interop/Raylib.cs, Raylib-cs/types/Raylib.Utils.cs
=> UnloadMesh needs a value, not a pointer

Examples/Textures/Bunnymark.cs
This PR is a small update to Bunnymark:
- MaxBunnies is now 500k
- it is possible to add *and remove* bunnies
- increment is now 500, decrement 2_500
- on-screen help how to interact is displayed
- performance slightly improved
- cognitive complexity (nesting, conditionals, etc.) of `static int Main()` reduced by 45%
- conflicting / outdated comments and constants cleaned up
- bunnies are now `record structs` in a `Span`
- removing bunnies shifts (copies) the Span in memory over the oldest ones
- screen bounce is done with a `switch` expression
- screen bounce logic is simplified
- large numeric constants use thousands separators
- TARGET_FPS is a constant now
- since the .csproj targets C# 12, I relied on language features available in C# 10 and up (which is the minimum due to …
=> Bunnymark refactored and cleaned up.

Raylib-cs/types/Color.cs
This pull request adds additional constructors for the Color class and documentation for them all.
=> Enhancement: Additional Color Constructors

Raylib-cs.Native/Raylib-cs.Native.csproj
=> Update Raylib-cs.Native.csproj #281
